FROM openjdk:17-slim
LABEL maintainer="Rokin Maharjan <rokinmaharjan@gmail.com>"
COPY target/api-gateway-0.0.1-SNAPSHOT.jar api-gateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/api-gateway-0.0.1-SNAPSHOT.jar"]