version: '2.1'
services:
  configserver:
    image: config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: eureka-server
    ports:
      - "8070:8070"
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 2
    depends_on:
      configserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "eurekaserver"
  microservice1:
    image: microservice1
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
      SERVER_PORT: "8080"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend
  microservice2:
    image: microservice2
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
      SERVER_PORT: "8081"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend
  microservice2_2:
    image: microservice2
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
      SERVER_PORT: "8083"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8083:8083"
    networks:
      - backend
  microservice3:
    image: microservice3
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
      SERVER_PORT: "8082"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - backend
  microservice3_2:
    image: microservice3
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8071"
      SERVER_PORT: "8084"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8084:8084"
    networks:
      - backend

networks:
  backend:
    driver: bridge