server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/


spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: microservice1
          uri: lb://microservice1
          predicates:
            - Path=/microservice1/**
          filters:
            - RewritePath=/microservice1/(?<path>.*), /$\{path}
        - id: microservice2
          uri: lb://microservice2
          predicates:
            - Path=/microservice2/**
          filters:
            - RewritePath=/microservice2/(?<path>.*), /$\{path}
        - id: microservice3
          uri: lb://microservice3
          predicates:
            - Path=/microservice3/**
          filters:
            - RewritePath=/microservice3/(?<path>.*), /$\{path}
            - SetResponseHeader= exampleHeaderKey, exampleHeaderValue
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1


management:
  endpoints:
    web:
      exposure:
        include: "*"
