FROM openjdk:17-slim
LABEL maintainer="Rokin Maharjan <rokinmaharjan@gmail.com>"
COPY target/microservice2-0.0.1-SNAPSHOT.jar microservice2-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/microservice2-0.0.1-SNAPSHOT.jar"]